{% set version = '0.4.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-xportr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/xportr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/xportr/xportr_{{ version }}.tar.gz
  sha256: f92c1777d812d8d6d12b401f92f97af14a5094af04e53f7edf6fa4082332f598

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    # The libstdc++.dll provided in libstdcxx v15.1.0 build h904f734_2
    # is missing `_ZSt21ios_base_library_initv`.
    # see: conda-forge/ctng-compilers-feedstock#174
    - libstdcxx !=14.3.0,!=15.1.0  # [win]
  host:
    - r-base
    - r-checkmate
    - r-cli
    - r-dplyr >=1.0.2
    - r-glue >=1.4.2
    - r-haven >=2.5.0
    - r-lifecycle
    - r-magrittr
    - r-purrr >=0.3.4
    - r-readr
    - r-rlang >=0.4.10
    - r-stringr >=1.4.0
    - r-tidyselect
  run:
    - r-base
    - r-checkmate
    - r-cli
    - r-dplyr >=1.0.2
    - r-glue >=1.4.2
    - r-haven >=2.5.0
    - r-lifecycle
    - r-magrittr
    - r-purrr >=0.3.4
    - r-readr
    - r-rlang >=0.4.10
    - r-stringr >=1.4.0
    - r-tidyselect
  run_constrained:
    - libstdcxx !=14.3.0,!=15.1.0           # [win]

test:
  commands:
    - $R -e "library('xportr')"           # [not win]
    - "\"%R%\" -e \"library('xportr')\""  # [win]

about:
  home: https://atorus-research.github.io/xportr/, https://github.com/atorus-research/xportr
  license: MIT
  summary: Tools to build CDISC compliant data sets and check for CDISC compliance.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
